### ISSUE TITLE
ID other than integer

### ISSUE THREAD

**Issue by jeans11** [donut-party/datapotato#2]
Hi! Can an ID be other than an `integer`. Maybe an `UUID` or `ObjectId`?

**Comment by flyingmachine** [comment]
Are you referring to examples like this?

```clojure
(def ID
  [:and {:gen/gen monotonic-id-gen} pos-int?])
```

If you are, then the short answer is yes :) You could have something like `(def ID uuid?)`. The longer answer is that it would probably be helpful to read [malli's docs](https://github.com/metosin/malli), as they more better explain what's going on here.

**Comment by jeans11** [comment]
Thanks @flyingmachine.
